# Generated by Django 5.2.10 on 2026-01-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20260116_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.PositiveIntegerField(blank=True, help_text='Enter salary in INR per month', null=True),
        ),
    ]
